[bin] some minor changes to dmenu scripts

diff --git a/bin/.bin/dmenu_vtc b/bin/.bin/dmenu_vtc
--- a/bin/.bin/dmenu_vtc
+++ b/bin/.bin/dmenu_vtc
@@ -1,39 +1,93 @@
 #!/bin/sh
 
 # check if running in X
-inx=$([ ! -z $XAUTHORITY ] && echo 1 || echo 0)
+INX=$([ ! -z $XAUTHORITY ] && echo 1 || echo 0)
 
-case $inx in
+ARGNAME=""
+
+LUMI="$(readvtc 0 | lumi)"
+
+BOTTOM=false
+PREGRAB=false
+CASEINSENSITIVE=false
+
+VERTICALLINES="0"
+HEIGHT="20"
+MONITOR=""
+PROMPT=""
+FONT="dnoxz_numerics:pixelsize=12:autohint=false"
+NFCOLOR="$(readvtc 6)"
+NBCOLOR="$([ "$LUMI" -gt 50 ] && printf '#fdfdfd' || printf '#030303')"
+SFCOLOR="$(readvtc 6)"
+SBCOLOR="$(readvtc 5)"
+WINDOW=""
+
+print_usage() {
+    echo "usage dmenu_vtc [-bfi] ..."
+}
+
+handle_name() {
+    ARGNAME=""
+    case "$1" in
+    # flag arguments
+    -b)     BOTTOM=true;;
+    -f)     PREGRAB=true;;
+    -i)     CASEINSSENSITIVE=true;;
+    # name/value arguments
+    -l | -h | -m | -p | -fn | -nb | -nf | -sb | -sf | -w)
+    ARGNAME="$1";;
+    esac
+}
+
+handle_value() {
+    case "$ARGNAME" in
+    -l)     VERTICALLINES="$1";;
+    -h)     HEIGHT="$1";;
+    -m)     MONITOR="$1";;
+    -p)     PROMPT="$1";;
+    -fn)    FONT="$1";;
+    -nf)    NFCOLOR="$1";;
+    -nb)    NBCOLOR="$1";;
+    -sf)    SFCOLOR="$1";;
+    -sb)    SBCOLOR="$1";;
+    -w)     WINDOW="$1";;
+    --)     break;;
+    -*)     echo "invalid option: $ARGNAME" 1>&2; exit 1;;
+    *)      break;;
+    esac
+    ARGNAME=""
+}
+
+# read arguments
+for var in "$@"; do
+    case "$var" in
+    --help) print_usage;;
+    -*)     handle_name "$var";;
+    *)      handle_value "$var";;
+    esac
+done
+
+case $INX in
 1)
     pgrep -x dmenu && exit
 
-    lumi="$(readvtc 0 | lumi)"
-    args="
-        -fn "hack:size=9"                                                   \
-        -nb $([ "$lumi" -gt 50 ] && printf '#fdfdfd' || printf '#030303')   \
-        -nf $(readvtc 6)                                                   \
-        -sb $(readvtc 5)                                                   \
-        -sf $(readvtc 6)"
+    ARGS="                                                                  \
+    $([ "$BOTTOM" = true            ] && echo "-b")                         \
+    $([ "$PREGRAB" = true           ] && echo "-f")                         \
+    $([ "$CASEINSSENSITIVE" = true  ] && echo "-i")                         \
+    "
 
-    while :; do
-        case "$1" in
-        -b | -f | -i)
-            args="$args $1";;
-        -l | -h | -m | -p | -fn | -nb | -nf | -sb | -sf)
-            args="$args $1"; shift; args="$args $1";;
-        -w)
-            args="$args $1"; shift; args="$args $(eval echo $1)";;
-        --)
-            shift; break;;
-        -*)
-            echo "invalid option: $1" 1>&2; exit 1;;
-        *)
-            break;;
-        esac
-        shift
-    done
-
-    dmenu${args}
+    dmenu   $ARGS                                                           \
+    -l      "$VERTICALLINES"                                                \
+    -h      "$HEIGHT"                                                       \
+    -m      "$MONITOR"                                                      \
+    -p      "$PROMPT"                                                       \
+    -fn     "$FONT"                                                         \
+    -nf     "$NFCOLOR"                                                      \
+    -nb     "$NBCOLOR"                                                      \
+    -sf     "$SFCOLOR"                                                      \
+    -sb     "$SBCOLOR"                                                      \
+    -w      "$WINDOW"
 ;;
 0)
     # fix for 'cascading' fzfs
